// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rectprismgrav
NumericMatrix rectprismgrav(NumericVector xstation, NumericVector ystation, NumericVector zstation, NumericVector xmin, NumericVector xmax, NumericVector ymin, NumericVector ymax, NumericVector zdeep, NumericVector zshallow, NumericVector deltarho, bool bycell);
RcppExport SEXP _gravmagsubs_rectprismgrav(SEXP xstationSEXP, SEXP ystationSEXP, SEXP zstationSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP, SEXP zdeepSEXP, SEXP zshallowSEXP, SEXP deltarhoSEXP, SEXP bycellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xstation(xstationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ystation(ystationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zstation(zstationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zdeep(zdeepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zshallow(zshallowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltarho(deltarhoSEXP);
    Rcpp::traits::input_parameter< bool >::type bycell(bycellSEXP);
    rcpp_result_gen = Rcpp::wrap(rectprismgrav(xstation, ystation, zstation, xmin, xmax, ymin, ymax, zdeep, zshallow, deltarho, bycell));
    return rcpp_result_gen;
END_RCPP
}
// rectprismmag
NumericMatrix rectprismmag(NumericVector xstation, NumericVector ystation, NumericVector zstation, NumericVector xmin, NumericVector xmax, NumericVector ymin, NumericVector ymax, NumericVector zdeep, NumericVector zshallow, NumericVector suscvolsi, NumericVector nrmstr, NumericVector nrmincl, NumericVector nrmdecl, NumericVector fieldtotal, NumericVector fieldincl, NumericVector fielddecl, bool bycell);
RcppExport SEXP _gravmagsubs_rectprismmag(SEXP xstationSEXP, SEXP ystationSEXP, SEXP zstationSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP, SEXP zdeepSEXP, SEXP zshallowSEXP, SEXP suscvolsiSEXP, SEXP nrmstrSEXP, SEXP nrminclSEXP, SEXP nrmdeclSEXP, SEXP fieldtotalSEXP, SEXP fieldinclSEXP, SEXP fielddeclSEXP, SEXP bycellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xstation(xstationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ystation(ystationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zstation(zstationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zdeep(zdeepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zshallow(zshallowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type suscvolsi(suscvolsiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nrmstr(nrmstrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nrmincl(nrminclSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nrmdecl(nrmdeclSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fieldtotal(fieldtotalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fieldincl(fieldinclSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fielddecl(fielddeclSEXP);
    Rcpp::traits::input_parameter< bool >::type bycell(bycellSEXP);
    rcpp_result_gen = Rcpp::wrap(rectprismmag(xstation, ystation, zstation, xmin, xmax, ymin, ymax, zdeep, zshallow, suscvolsi, nrmstr, nrmincl, nrmdecl, fieldtotal, fieldincl, fielddecl, bycell));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gravmagsubs_rectprismgrav", (DL_FUNC) &_gravmagsubs_rectprismgrav, 11},
    {"_gravmagsubs_rectprismmag", (DL_FUNC) &_gravmagsubs_rectprismmag, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_gravmagsubs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
