# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rectprismgrav <- function(xstation, ystation, zstation, xmin, xmax, ymin, ymax, zdeep, zshallow, deltarho, bycell = FALSE) {
    .Call(`_gravmagsubs_rectprismgrav`, xstation, ystation, zstation, xmin, xmax, ymin, ymax, zdeep, zshallow, deltarho, bycell)
}

rectprismmag <- function(xstation, ystation, zstation, xmin, xmax, ymin, ymax, zdeep, zshallow, suscvolsi, nrmstr, nrmincl, nrmdecl, fieldtotal, fieldincl, fielddecl, bycell = FALSE) {
    .Call(`_gravmagsubs_rectprismmag`, xstation, ystation, zstation, xmin, xmax, ymin, ymax, zdeep, zshallow, suscvolsi, nrmstr, nrmincl, nrmdecl, fieldtotal, fieldincl, fielddecl, bycell)
}

